language: java
install: true
env:
  global:
    - APP_NAME=rogue

jdk:
  - openjdk8

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)